FROM jupyter/all-spark-notebook:python-3.11.5

USER root

# RUN curl -O https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz \
#     && tar zxvf spark-3.4.1-bin-hadoop3.tgz \
#     && rm -rf spark-3.4.1-bin-hadoop3.tgz \
#     && (cd spark-3.4.1-bin-hadoop3 && tar c .) | (cd /usr/local/ && tar xf -) \
#     && rm -rf /usr/local/spark \
#     && ln -s /usr/local/spark-3.4.1-bin-hadoop3 /usr/local/spark

RUN curl -O https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz \
    && mv spark-3.4.1-bin-hadoop3.tgz /usr/local/ \
    && rm -rf /usr/local/spark \
    && tar zxvf /usr/local/spark-3.4.1-bin-hadoop3.tgz \
    && rm -rf /usr/local/spark-3.4.1-bin-hadoop3.tgz \
    && ln -s /usr/local/spark-3.4.1-bin-hadoop3 /usr/local/spark

RUN curl -O https://repo1.maven.org/maven2/software/amazon/awssdk/s3/2.18.41/s3-2.18.41.jar \
    && curl -O https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.12.367/aws-java-sdk-1.12.367.jar \
    && curl -O https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar \
    && curl -O https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.2.0/delta-core_2.12-2.2.0.jar \
    && curl -O https://repo1.maven.org/maven2/io/delta/delta-storage/2.2.0/delta-storage-2.2.0.jar \
    && curl -O https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.2/hadoop-aws-3.3.2.jar \
    && curl -O https://repo1.maven.org/maven2/com/microsoft/azure/spark-mssql-connector_2.12/1.3.0-BETA/spark-mssql-connector_2.12_3.0-1.0.0-alpha.jar \
    && mv s3-2.18.41.jar /usr/local/spark/jars \
    && mv aws-java-sdk-1.12.367.jar /usr/local/spark/jars \
    && mv aws-java-sdk-bundle-1.11.1026.jar /usr/local/spark/jars \
    && mv delta-core_2.12-2.2.0.jar /usr/local/spark/jars \
    && mv delta-storage-2.2.0.jar /usr/local/spark/jars \
    && mv hadoop-aws-3.3.2.jar /usr/local/spark/jars \
    && mv spark-mssql-connector_2.12_3.0-1.0.0-alpha.jar /usr/local/spark/jars
